services:
  mysql:
    image: ougraduation/mysql:8.0.36
    ports:
      - 3307:3306
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./server/database/current_db:/docker-entrypoint-initdb.d
    networks:
      - keycloak-and-mysql-network

  keycloak:
    image: ougraduation/keycloak-service:24.0.2
    command: start-dev
    restart: unless-stopped
    container_name: keycloak
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak_auth_service_db
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=admin
      - KC_TRANSACTION_XA_ENABLED=true
      - QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY=true
      - KC_HOSTNAME_URL=http://localhost:8080
      - KC_HOSTNAME_ADMIN_URL=http://localhost:8080
      - KC_PROXY=edge
      - KC_LOG_LEVEL=debug
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
    depends_on:
      - mysql
    networks:
      - keycloak-and-mysql-network

  discovery-server:
    image: ougraduation/discovery-server:latest
    container_name: discovery-server
    pull_policy: always
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - keycloak-and-mysql-network

  api-gateway:
    image: ougraduation/api-gateway:latest
    container_name: api-gateway
    pull_policy: always
    ports:
      - 8181:8080
    expose:
      - 8181
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
    depends_on:
      - discovery-server
    networks:
      - keycloak-and-mysql-network

  chat-bot-service:
    image: ougraduation/chatbot-service:latest
    container_name: chat-bot-service
    restart: unless-stopped
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - discovery-server
      - api-gateway
      - keycloak
    networks:
      - keycloak-and-mysql-network

  schedule-service:
    image: ougraduation/schedule-service:latest
    container_name: schedule-service
    restart: unless-stopped
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - discovery-server
      - api-gateway
      - keycloak
    networks:
      - keycloak-and-mysql-network

  client-frontend:
    image: ougraduation/client:latest
    container_name: client-frontend
    restart: unless-stopped
    pull_policy: always
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:

volumes:
  mysql-volume: