services:
  mysql-kc:
    image: mysql:8.0.36
    ports:
      - 3307:3306
    restart: unless-stopped
    container_name: kcdb
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: keycloak_auth_service_db
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev
    restart: unless-stopped
    ports:
      - 8181:8080
    environment:
      # - KEYCLOAK_USER=user
      # - KEYCLOAK_PASSWORD=user
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://kcdb:3306/keycloak_auth_service_db
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=admin
      # - KC_DB_ROOT_PASSWORD=admin
      - KC_Hostname=localhost
      - KC_TRANSACTION_XA_ENABLED=true
      - QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY=true
      # - DB_VENDOR=MYSQL
      # - DB_ADDR=mysql-kc
      # - DB_PORT=3306
      # - DB_USER=user
      # - DB_PASSWORD=admin
      # - DB_DATABASE=keycloak
    depends_on:
      - mysql-kc
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume: