name: Dockerize Chatbot Service

on:
  push:
    branchs: [main]
    paths:
      - server/chatbot-service/**  # Only trigger on changes within chatbot-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/chatbot-service
    steps:
      - uses: actions/checkout@v3

      - name: Set up Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Clean project
        run: mvn clean

      - name: Install dependencies
        run: mvn install
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image (using Jib)
        run: mvn jib:build