# THIS TEMPLATE IS USE FOR JAVA - MAVEN PROJECT ONLY

name: Dockerize Schedule Service

on:
  pull_request:
    types: [opened]
    branchs: [main] # Targeted branch to listen on --> Default is main
    paths:
      - server/schedule-service/** 

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Leave this as it is
    defaults:
      run:
        working-directory: ./server/schedule-service # Path to the actual service you want to Dockerize
    steps:
      - uses: actions/checkout@v3 # 1st action: checkout newest code on targeted branch

      - name: Set up Maven cache # 2nd action: setup maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK # 3rd action: setup jdk --> change 'java-version' to your targeted version
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Clean project # 4th action: clean
        run: mvn clean

      - name: Install dependencies # 5th action: install dependencies
        run: mvn install
      
      - name: Login to Docker Hub # 6th action: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Change this in Repository setting > Secrets > Action Secrets if needed
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Dockerize (using Jib) # 7th action: dockerize
        run: mvn jib:build